# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
      target: final
      args:
        - YT_DLP_NAME=yt-dlp
    ports:
      - 8080:8080
    environment:
      - YOUTUBE_PROXY=${YOUTUBE_PROXY:?must include proxy}
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY:?must include OpenAI API key}
      - OPEN_AI_BASE_URL=${OPEN_AI_BASE_URL:? must include OpenAI base URL}
      - OPEN_AI_MODEL=${OPEN_AI_MODEL:? must include OpenAI model}
      - DB_USERNAME=postgres
      - DB_NAME=example
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.5
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
