name: verify

on:
  pull_request:
    branches:
      - main
      - "**"
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always
  TOOLCHAIN: stable
  SQLX_OFFLINE: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2

      - name: check formatting
        run: just format-check

  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v5
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2

      - name: lint
        run: just lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2

      - name: build
        run: cargo build --release --verbose
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.5
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres" # TODO remove after migrating other DB tests to use spawn_app
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5432"
      DB_HOST: "localhost"
      DB_NAME: "postgres"

    steps:
      - uses: actions/checkout@v5
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2

      - name: test
        run: cargo test --verbose
